image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      yarn run bootstrap &&
      cd ./examples/gatsbygram &&
      yarn install &&
      gatsby-dev --set-path-to-repo ../.. &&
      gatsby-dev --scan-once &&
      npx gatsby build &&
      cd ../.. &&
      gp sync-done build
    command: >
      yarn run watch --scope={gatsby,gatsby-image,gatsby-link}
  - openMode: split-right
    before: >
      cd ./examples/gatsbygram
    command: >
      gp await-port 8000 &&
      gatsby-dev --set-path-to-repo ../.. &&
      gatsby-dev
  - before: >
      cd ./examples/gatsbygram
    init: >
      gp sync-await build
    command: >
      npx gatsby develop
ports:
  - port: 8000
    onOpen: open-preview
  - port: 31997 # yarn mutex
    onOpen: ignore
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
