language: node_js
node_js:
  - "6"
  - "8"

os: [linux]
dist: trusty
sudo: required

before_install:
  - npm i -g yarn@latest

install:
  - yarn run bootstrap

script:
  - npm test

after_success:
  - yarn run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
