language: node_js
node_js:
  - "4"
  - "6"
  - "7"

os: [linux, osx]
dist: trusty
sudo: required

cache:
  directories:
    - ~/.npm

before_install:
  - npm i -g npm@5

install:
  - npm install

script:
  - npm test
