# branches to build
branches:
  # whitelist
  only:
    - 1.0
    - master

platform:
  - Any CPU

environment:
  nodejs_version: "6"

  matrix:
#  - example: client-only-paths

#  - example: gatsbygram

  - example: hn

#  - example: no-plugins

#  - example: no-trailing-slashes

#  - example: using-drupal

#  - example: using-postcss-sass



# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install -g windows-build-tools
  - ps: npm install -g node-gyp
  - ps: npm install -g gatsby-dev-cli@canary
  - ps: git checkout 1.0
  - ps: npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run build
  - cd examples/%example%
  - npm install
  - gatsby-dev --set-path-to-repo ../..
  - gatsby-dev --scan-once
  - npm test
  - npm run build


# Don't actually build.
build: off
deploy: off
