aliases:
  node6: &node6
    docker:
      - image: circleci/node:6

  node8: &node8
    docker:
      - image: circleci/node:8

  node10: &node10
    docker:
      - image: circleci/node:10

  node10_browsers: &node10_browsers
    docker:
      - image: circleci/node:10-browsers

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - node-modules-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: |
        yarn

  persist_node_modules: &persist_node_modules
    save_cache:
      name: Save node modules cache
      key: node-modules-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: packages

  ignore_master: &ignore_master
    filters:
      branches:
        ignore:
          - master

  test_template: &test_template
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|integration-tests/*"
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - <<: *attach_to_bootstrap
      - run: yarn jest -w 1

  integration_test_template: &integration_test_template
    <<: *node10_browsers
    <<: *attach_to_bootstrap
    <<: *ignore_master

version: 2

jobs:
  bootstrap:
    <<: *node10
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|integration-tests/*"
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn bootstrap
      - persist_to_workspace:
          root: packages
          paths:
            - '*'

  lint:
    <<: *node10
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn lint

  testNode6:
    <<: *node10
    <<: *test_template

  testNode8:
    <<: *node8
    <<: *test_template

  testNode10:
    <<: *node10
    <<: *test_template

  integration:
    <<: *node10
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|integration-tests/*"
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn test:integration

  e2e:path-prefix:
    <<: *integration_test_template
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|integration-tests/*"
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: ./scripts/integration-test.sh integration-tests/path-prefix
  
  e2e:gatsby-image:
    <<: *integration_test_template
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|integration-tests/*"
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: ./scripts/integration-test.sh integration-tests/gatsby-image
  
  e2e:production_runtime:
    <<: *integration_test_template
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|integration-tests/*"
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: ./scripts/integration-test.sh integration-tests/production-runtime

workflows:
  version: 2
  build-test:
    jobs:
      - bootstrap
      - lint
      - testNode6:
          requires:
            - bootstrap
      - testNode8:
          requires:
            - bootstrap
      - testNode10:
          requires:
            - bootstrap
      - integration
      - e2e:path-prefix:
          <<: *ignore_master
          requires:
            - bootstrap
      - e2e:gatsby-image:
          <<: *ignore_master
          requires:
            - bootstrap
      - e2e:production_runtime:
          <<: *ignore_master
          requires:
            - bootstrap
