orbs:
  win: circleci/windows@2.4.0

executors:
  node:
    parameters:
      image:
        type: string
        default: "18.0.0"
      gatsby_major:
        type: string
        default: "5"
    docker:
      - image: cimg/node:<< parameters.image >>
    environment:
      GATSBY_CPU_COUNT: 2
      COMPILER_OPTIONS: GATSBY_MAJOR=<< parameters.gatsby_major >>
      NODE_NO_WARNINGS: 1

aliases:
  e2e-executor-env: &e2e-executor-env
    GATSBY_CPU_COUNT: 2
    VERBOSE: 1

  e2e-executor: &e2e-executor
    docker:
      - image: cypress/browsers:node18.6.0-chrome105-ff104
    environment:
      <<: *e2e-executor-env

  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cypress-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn

  check_lockfile: &check_lockfile
    run:
      name: Check for dirty lockfile
      command: ./scripts/check-lockfile.sh || exit 1

  validate_renovate: &validate_renovate
    run:
      name: Validate renovate-config
      command: (node scripts/renovate-config-generator.js && (git status --porcelain renovate.json5 | grep "M renovate.json5")) && (echo "Please run \"node scripts/renovate-config-generator.js\" to update renovate.json5" && exit 1) || npx -p renovate@31.28.5 renovate-config-validator .

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cypress-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: ./

  ignore_master: &ignore_master
    filters:
      branches:
        ignore:
          - master

  ignore_docs: &ignore_docs
    filters:
      branches:
        ignore:
          - /docs.+/

  test_template: &test_template
    parallelism: 4
    parameters:
      npm_rebuild:
        type: boolean
        default: false
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      - <<: *attach_to_bootstrap
      - when:
          condition: << parameters.npm_rebuild >>
          steps:
            - run: npm rebuild
      - run:
          name: Step debug info
          command: |
            yarn list react
            yarn why lmdb-store
      - run:
          name: Run tests
          command: yarn jest --ci --runInBand  $(yarn -s jest --listTests | sed 's/\/home\/circleci\/project\///g' | circleci tests split)
          environment:
            NODE_OPTIONS: --max-old-space-size=2048
            GENERATE_JEST_REPORT: "true"
            JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
            JEST_JUNIT_OUTPUT_NAME: results.xml
            JEST_JUNIT_REPORT_TEST_SUITE_ERRORS: "true"
      - store_test_results:
          path: ./test-results/jest-node/

  e2e-test-workflow: &e2e-test-workflow
    filters:
      branches:
        ignore:
          - master
          - /docs.+/
    requires:
      - lint
      - typecheck
      - unit_tests_node18

commands:
  e2e-test:
    parameters:
      skip_file_change_test:
        type: boolean
        default: false
      trigger_pattern:
        type: string
        default: "packages/*|.circleci/*|scripts/e2e-test.sh"
      test_path:
        type: string
      test_command:
        type: string
        default: "yarn test"
      react_version:
        type: string
        default: ""
      slices:
        type: boolean
        default: true # allow disabling it later when setting up partial hydration tests
    steps:
      - checkout
      # In case of failure, add these steps again. Cache probably got deleted
      #- <<: *restore_cache
      #- <<: *install_node_modules
      #- <<: *persist_cache
      - unless:
          condition: << parameters.skip_file_change_test >>
          steps:
            - run: ./scripts/assert
