aliases:
  node10: &node10
    docker:
      - image: circleci/node:10

  node10_browsers: &node10_browsers
    docker:
      - image: circleci/node:10-browsers

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - node-modules-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: |
        yarn

  persist_node_modules: &persist_node_modules
    save_cache:
      name: Save node modules cache
      key: node-modules-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: packages

  ignore_master: &ignore_master
    branches:
      ignore:
        - master

version: 2

jobs:
  bootstrap:
    <<: *node10
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn bootstrap
      - persist_to_workspace:
          root: packages
          paths:
            - '*'

  lint:
    <<: *node10
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn lint

  test:
    <<: *node10
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - <<: *attach_to_bootstrap
      - run: yarn jest -w 1

  integration:
    <<: *node10
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn test:integration

  e2e:path-prefix:
    <<: *node10_browsers
    <<: *ignore_master
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: ./scripts/integration-test.sh integration-tests/path-prefix
  
  e2e:gatsby-image:
    <<: *node10_browsers
    <<: *ignore_master
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: ./scripts/integration-test.sh integration-tests/gatsby-image
  
  e2e:production_runtime:
    <<: *node10_browsers
    <<: *ignore_master
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: ./scripts/integration-test.sh integration-tests/production-runtime

workflows:
  version: 2
  build-test:
    jobs:
      - bootstrap
      - lint
      - test:
          requires:
            - bootstrap
      - integration
      - run-e2e:
          <<: *ignore_master
          type: approval
          requires:
            - bootstrap
            - lint
            - test
            - integration
      - e2e:path-prefix:
          requires:
            - run-e2e
      - e2e:gatsby-image:
          requires:
            - run-e2e
      - e2e:production_runtime:
          requires:
            - run-e2e
