version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: "Lint"
          command: |
            yarn
            yarn lint
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: "Unit test"
          command: |
            yarn bootstrap
            yarn jest -w 1
  integration:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: "Integration tests"
          command: |
            yarn
            yarn test:integration
  e2e:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: "e2e tests"
          command: |
            yarn
            npm install -g gatsby-dev-cli
            ./scripts/run-integration-tests.sh


workflows:
  version: 2
  build-test:
    jobs:
      - lint
      - test
      - integration
      - approve-e2e:
          type: approval
          requires:
            - lint
            - test
            - integration
      - e2e:
          requires:
            - approve-e2e
