name: Bug Report
description: Something isn't working as expected? Report your bugs here.
labels: "type: bug"
body:
- type: markdown
  attributes:
    value: |
      # Welcome 👋 
      
      Thanks for taking the time to fill out this bug report.
      Please fill out each section below. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible. Otherwise we might need to close the issue without e.g. clear reproduction steps.
      
      Also please verify that your issue is present in `gatsby@next`, too. The `next` version is the latest beta version of Gatsby and has any pending changes that are in the next stable release.
      
      Useful Links:
      - Documentation: https://www.gatsbyjs.com/docs/
      - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/
- type: checkboxes
  attributes:
    label: Preliminary Checks
    description: Please make sure that you verify each checkbox and follow the instructions in them.
    options:
      - label: "This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues"
        required: true
      - label: "This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions"
        required: true
- type: textarea
  attributes:
    label: Description
    description: Describe the issue that you're seeing.
  validations:
    required: true
- type: input
  id: reproduction-link
  attributes:
    label: Reproduction Link
    description: "Link to a reproduction (GitHub repository, Codesandbox, etc.). How to make a minimal reproduction: https://gatsby.dev/reproduction"
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Clear steps describing how to reproduce the issue.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Result
    description: Describe what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Result
    description: Describe what actually happened.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    render: shell
    description: Run "gatsby info --clipboard" in your project directory and paste the output here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Config Flags
    description: Do you use any "flags" inside "gatsby-config.js"? If yes, please paste them here.
  validations:
    required: false
