name: Spelling

on:
  pull_request:
    paths:
      - "docs/**"
      - "starters/**"

jobs:
  codespell:
    name: Check spelling of docs & starters with codespell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check spelling with codespell
        run: codespell --ignore-words=codespell.txt --skip="./.yarn/**,./yarnrc,./yarn.lock,./benchmarks/**,./deprecated-packages/**,./e2e-tests/**,./examples/**,./integration-tests/**,./packages/**,./scripts/**,./starters/**/package-lock.json,./.github/**" || exit 1
